### ISSUE TITLE
Create Atom linter for example-process

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#17]
Depends on #24 

Create an Atom linter that uses the `example-process` program from Atom.

![Preview](http://g.recordit.co/13RfmirPz2.gif)

Documentation: https://github.com/steelbrain/linter/tree/v1/docs

Discussion: https://github.com/steelbrain/linter/issues/1298

Then people with STAT-compliant programs will have a VERY simple way to make their program compatible with Atom. They will only need to copy our example linter and change the name of the program that is run.

## Work plan

 - [ ] Make copy of https://github.com/sirbrillig/linter-mixed-indent and get it working in Atom
 - [ ] Find a javascript library that can read JSON streams
 - [ ] Call our `example-process` from the linter
    - You can probably find a better example than `linter-mixed-indent` which already handles calling an external program
 - [ ] Update README.md so it is clear how others can copy and easily extend our work to use their own STAT compliant tool

Verify that this tool works correctly by using Atom and creating an animated gif (I use `licecap`). It should show one finding after 1 second, a second finding after a further 2 seconds and the final finding is shown after a further 3 seconds. It should NOT wait 6 seconds and show all three findings.

**Comment by fulldecent** [comment]
Regarding the work item "Find a javascript library that can read JSON streams", here is one such library: http://rapidjson.org/md_doc_sax.html

There may also be another one that is better suited for our use.

**Comment by ilyalyo** [comment]
Now I think we don't need any third party library, parsing can be done same as in stat-reader ruby implementation https://github.com/fulldecent/structured-acceptance-test/blob/master/tools/example-consumer/stat-reader/stat-reader.rb#L64-L83
Working example:
![stat](https://cloud.githubusercontent.com/assets/11000048/23030871/20e28fba-f480-11e6-96d6-23c5e2d5afd2.gif)

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/structured-acceptance-test/pull/34

**Comment by fulldecent** [comment]
Looks good, thank you
