### ISSUE TITLE
Update Ruby implementation to support pretty output

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#26]
Currently our Ruby implementation only supports JSON output. This is great for consumers, but linters prefer a more friendly looking output by default.

Let's make a great looking output option and add it into the Ruby implementation. It should look so good that linters will want to use our STAT implementation just to get this beautiful output.

![screen shot 2017-01-13 at 2 38 42 pm](https://cloud.githubusercontent.com/assets/382183/21943163/ff42e294-d99d-11e6-80af-a7a295cf3b0f.png)

## Work plan

 - [x] Document all possible output situations and required output formatting
    - Processes 
      - A process with only a name
         `⭐️ web-puc`
      - A process with a name and a version
         `⭐️ web-puc, version 0.0.2` 
      - (Other information is not used.)
    - Findings
      - With failure set to true
         `🛑 Rule, description` (entire line is red)
      - With failure set to false
         `⚠️ Rule, description` (entire line is yellow)
      - With rule, description and location (location only has file name)
         `⚠️ Rule, description` (entire line is yellow)
         `  in index2.php`
      - With rule, description and location (location is one line)
         `⚠️ Rule, description` (entire line is yellow)
         `  in index2.php, line 24`
      - With rule, description and location (location is multiple lines)
         `⚠️ Rule, description` (entire line is yellow)
         `  in index2.php, lines 24-26`
      - With rule, description and location (location is columns on one line)
         `⚠️ Rule, description` (entire line is yellow)
         `  in index2.php, line 24:15-18`
      - With rule, description and location (location is columns on multiple lines)
         `⚠️ Rule, description` (entire line is yellow)
         `  in index2.php, line 24:15 to line 25:5`
      - With recommendation
         `⚠️ Rule, description` (entire line is yellow)
         `  RECOMMENDATION: Reword to avoid the passive voice.`
      - (Other finding information is not used.)
   - Summaries
     - No errors, no warnings
        `✅ PASSED with no warnings` (whole line is green)
     - No errors, with warnings
        `⚠️ PASSED with 5 warnings` (whole line is yellow)
     - With errors, no warnings
        `🛑 FAILED with 5 errors` (whole line is red)
     - With errors, with warnings
        `🛑 FAILED with 5 errors and 1 warning` (whole line is red)
 - [x] Update our Ruby implement to add this outputting option
 - [x] Update example consumer from #25 to use this new outputting format

## Follow-on work

 - [x] Create pull requests for other projects to use our new Gem and use our pretty output format by default
    - [x] https://github.com/mcandre/lili
    - [x] https://github.com/mcandre/gtdlint
    - [x] https://github.com/mcandre/cowl
    - [x] https://github.com/mcandre/enlint
    - [x] https://github.com/mcandre/aspelllint
    - [x] web-puc
 - [ ] Begin looking for other projects that we may recommend to adopt STAT.

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/structured-acceptance-test/pull/29
Updated example-consumer for for different possible cases.

**Comment by ilyalyo** [comment]
Also added this PR https://github.com/fulldecent/structured-acceptance-test/pull/32
with fix error symbol utf code

**Comment by ilyalyo** [comment]
Added PR to mcandre/lili: https://github.com/mcandre/lili/issues/22

**Comment by ilyalyo** [comment]
About web-puc, it's written on shell, so it can not use new STAT gem.

**Comment by ilyalyo** [comment]
Added PR with pretty json for print_* methods: https://github.com/fulldecent/structured-acceptance-test/pull/35

**Comment by fulldecent** [comment]
Please see https://github.com/fulldecent/web-puc/issues/5

**Comment by ilyalyo** [comment]
All points are done except:
Begin looking for other projects that we may recommend to adopt STAT.

**Comment by fulldecent** [comment]
LGTm, closing, thank you
